// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axsklzyzmcqipmjfhweh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4c2tsenl6bWNxaXBtamZod2VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNzY5OTQsImV4cCI6MjA2NTg1Mjk5NH0.BQz__f_MfQPZYkaq6PCgVr9oX32mvhLOxb6Jp3Yu0zQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);